### ISSUE TITLE
UnboundLocalError: local variable 'info' referenced before assignment

### ISSUE THREAD

**Issue by jeromesteve202** [theriley106/SneakerBotTutorials#5]
I cloned the latest project and I am able to run the app.py. I made sure to change the BeautifulSoup so that it uses an html parser. However, after making those changes I am getting an error that says `UnboundLocalError: local variable 'info' referenced before assignment`. Is there a problem with the code or am I doing something wrong?

**Comment by mdbkio** [comment]
I got the same error. Need to change BeautifulSoup([your markup]) to : BeautifulSoup([your markup], "lxml")

**Comment by osbornedesign** [comment]
Where do you make that change?

**Comment by jeromesteve202** [comment]
Yea, that's what I was going to ask because I don't know where exactly I have to change that.

**Comment by theriley106** [comment]
Hey guys!  So sorry about that.  I added the ability to add proxies as System arguments and didn't document anything in the README.

I fixed the code so that info is defined before looking for sys arguments.  

@masdafmafia Thanks for the heads up!  I fixed this as well.

I'm going to go ahead and close this issue, but let me know if you guys have any more issues.

Best,
Christopher
